# Generated by Django 6.0.2 on 2026-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopomodoro',
            name='duracao_minutos',
            field=models.IntegerField(default=60),
        ),
    ]
